name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        BUILD_TARGET: [dev, release]

    steps:
    - uses: actions/checkout@v4
    - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode.
      run: cargo build --verbose --profile "${{ matrix.BUILD_TARGET }}"
    - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode.
      run: cargo test --verbose --profile "${{ matrix.BUILD_TARGET }}"
